<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>Profitocracy.Mobile</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>
    <ApplicationTitle>Profitocracy</ApplicationTitle>
    <ApplicationId>com.krawmire.profitocracy</ApplicationId>
    <ApplicationVersion>50</ApplicationVersion>
    <ApplicationDisplayVersion>1.14.2</ApplicationDisplayVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
    <DefaultResourcesNamespace>Profitocracy.Mobile.Resources.Strings</DefaultResourcesNamespace>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Profitocracy.Core\Profitocracy.Core.csproj" />
    <ProjectReference Include="..\Profitocracy.Infrastructure\Profitocracy.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="12.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc5.4" />
    <PackageReference Include="Meziantou.Framework.ResxSourceGenerator" Version="1.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.90" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.90" />
    <PackageReference Include="Plugin.Maui.AppRating" Version="1.2.1" />
    <PackageReference Include="Plugin.LocalNotification" Version="12.0.2" />
    <PackageReference Include="Plugin.Maui.Biometric" Version="0.0.7" />
    <!-- Development dependencies -->
    <PackageReference Condition="'$(Configuration)' != 'Release'" Include="Microsoft.Extensions.Logging.Debug" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" BaseSize="128,128" Resize="false" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#ffffff" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" BaseSize="500,575" Resize="false" Color="#ffffff" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <!-- Used by tab bar -->
    <MauiImage Update="Resources\Images\home.png" BaseSize="24,24" />
    <MauiImage Update="Resources\Images\transactions.png" BaseSize="24,24" />
    <MauiImage Update="Resources\Images\settings.png" BaseSize="24,24" />
    <MauiImage Update="Resources\Images\chart.png" BaseSize="24,24" />
    <!-- Used by the rest of the application -->
    <MauiImage Update="Resources\Images\bin.png" BaseSize="20,20" />
    <MauiImage Update="Resources\Images\edit.png" BaseSize="20,20" />
    <MauiImage Update="Resources\Images\currencies.png" BaseSize="20,20" />
  </ItemGroup>
  <ItemGroup>
    <!-- Enable the source generator for all resx files in the project -->
    <AdditionalFiles Include="**/*.resx" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Work.Runtime">
      <Version>2.10.2</Version>
    </PackageReference>
  </ItemGroup>
</Project>